### ISSUE TITLE
White/Black list options configuration : UI & UX improvement suggestions

### ISSUE THREAD

**Issue by Jean-Ricky** [dsrini-open/history-delete#11]
it's a bit puzzling - at first time, to understand the options
suggestions to improve the UI - UX :
- lay out options based on White/Black list distinction rather than Menu/Action configurations 
- allow/freeze ( & dim) options when depending on whether another/above one is on/off

**Comment by dsrini-open** [comment]
Plugin allows to remove history based out of both whitelist, and blacklist rather than either/or. 

This allows one to have both configs thereby enabling users to remove all history but whitelist without having to remove blacklist option. 
Also, the scenario above would cause to remove all whitelist sites to remove before blacklist sites thereby loosing some previously saved config. 

The current set of options gives many ways to configure than restricting users to follow either/or list.

**Comment by Jean-Ricky** [comment]
reading myself back, I realize that one could understand what I wrote as you did
but I did not mean 
- exclusive or : XOR : either one or the other
- instead of inclusive or : OR : either anyone or both
(even if I can't figure out a use case for using both : black AND white ...)

what I did mean might be clearer with this explicit configuration menu alternative :
- Enable removing of current website from history
---
- Enable Blacklisting of current host/domain & Removing at Will of Blacklist entries From history 
- Enable Automatic removal of Blacklist entries from history upon Quitting browser
 (toggling allowed if above option is ON)
---
- Enable Whitelisting of current host/domain & Clearing at Will whole history But Whitelist entries
- Enable Reminders to Clear whole history But Whitelist entries
(toggling allowed if above option is ON)
- Frequency (hour/s) : 1 - 24/48
(specification allowed if above option is ON)

is it ?
could it help to make the User eXperience even more enjoyable ?
